all: floats integers mems passive active

passive: passive.c
	gcc -o passive passive.c

active: active.c
	gcc -o active active.c

floats: floats.c
	gcc -o floats floats.c

integers: integers.c
	gcc -o integers integers.c

mems: mems.c
	gcc -o mems mems.c

clean:
	rm -f floats integers mems
