all: iochars iochars-v2 ioints copyFile1

iochars: iochars.c
	gcc -o iochars iochars.c

iochars-v2: iochars-v2.c
	gcc -o iochars-v2 iochars-v2.c 

ioints: ioints.c
	gcc -o ioints ioints.c

copyFile1: copyFile1.c
	gcc -o copyFile1 copyFile1.c

clean:
	rm -r iochars