all: writeint writebin readchar readbin utf8coding floatdiv ages-struct

writeint: writeint.c
	gcc -o writeint writeint.c

writebin: writebin.c
	gcc -o writebin writebin.c

readchar: readchar.c
	gcc -o readchar readchar.c

readbin: readbin.c
	gcc -o readbin readbin.c

utf8coding: utf8coding.c
	gcc -o utf8coding utf8coding.c

floatdiv: floatdiv.c
	gcc -o floatdiv floatdiv.c

ages-struct: ages-struct.c
	gcc -o ages-struct ages-struct.c

ages-union: ages-union.c
	gcc -o ages-union ages-union.c
