all: writeint writebin readchar readbin utf8coding

writeint: writeint.c
	gcc -o writeint writeint.c

writebin: writebin.c
	gcc -o writebin writebin.c

readchar: readchar.c
	gcc -o readchar readchar.c

readbin: readbin.c
	gcc -o readbin readbin.c

utf8coding: utf8coding.c
	gcc -o utf8coding utf8coding.c