all: exercise1 exercise2B exercise3A exercise3B exercise3C exercise3D exercise3E exercise3F 
exercise1: exercise1.c
	gcc -o exercise1 exercise1.c -fopenmp

exercise3A: exercise3A.c
	gcc -o exercise3A exercise3A.c -fopenmp

exercise3B: exercise3B.c
	gcc -o exercise3B exercise3B.c -fopenmp

exercise3C: exercise3C.c
	gcc -o exercise3C exercise3C.c -fopenmp

exercise2B: exercise2B.c
	gcc -o exercise2B exercise2B.c -fopenmp

exercise3D: exercise3D.c
	gcc -o exercise3D exercise3D.c -fopenmp

exercise3E: exercise3E.c
	gcc -o exercise3E exercise3E.c -fopenmp

exercise3F: exercise3F.c
	gcc -o exercise3F exercise3F.c -fopenmp

clean:
	rm -r exercise1 exercise2B exercise3A exercise3B  exercise3C exercise3D exercise3E exercise3F 